spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notificationdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      properties:
        retry.backoff.ms: 3000
        reconnect.backoff.ms: 3000

server:
  port: 8081

sendgrid:
  api:
    key: ${SENDGRID_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

